server:
  port: 8080

## 后台服务的域名， 配置为网关的域名
backend:
  server: http://spring-cloud-gateway-service # 发现场景
#  server: http://6cp0b5ata6xutdud.kouzhe.cn-north-4.huaweicse.com # CDN 场景
  enableDiscovery: true

spring:
  application:
    name: structs-website
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-south-1.myhuaweicloud.com
        appName: discovery
        serviceName: structs-website
        version: 0.0.1
        watch: false
      config:
        serverAddr: https://cse.cn-south-1.myhuaweicloud.com
        watch:
          delay: 10000
      credentials:
        enabled: true
        accessKey: your access key
        secretKey: your secret key
        akskCustomCipher: default
        project: cn-south-1