PAAS_CSE_SC_ENDPOINT: http://127.0.0.1:30100
PAAS_CSE_CC_ENDPOINT: http://127.0.0.1:30113

#### 服务配置信息 ####
dubbo:
  servicecomb:
    service:
      application: basic-application # 所属应用。
      name: price-provider   # 服务名称。
      version: 1.0.0   # 版本。默认为 1.0.0.0
      # environmen: production # 环境。默认为空。可选值：development, testing, acceptance, production
      # project: # project。 默认为 default
      # instance:
      # initialStatus: UP # 实例初始状态。可选值： UP, DOWN, STARTING, OUTOFSERVICE

    registry:
      address: ${PAAS_CSE_SC_ENDPOINT}
    config:
      address: ${PAAS_CSE_CC_ENDPOINT}

#    ssl:
#      enabled: true
#      credentials:
#        enabled: true
#        accessKey: your access key
#        secretKey: your secret key
#        cipher: default
#        project: cn-north-1
